// Code generated by ragel DO NOT EDIT.

//.... lightning/mydump/csv_parser.rl:1
// Please edit `csv_parser.rl` if you want to modify this file. To generate
// `csv_parser_generated.go`, please execute
//
// ```sh
// make data_parsers
// ```

package mydump

import (
	"io"

	"github.com/pingcap/errors"
)


//.... lightning/mydump/csv_parser.rl:57



//.... tmp_parser.go:24
const csv_parser_start int = 8
const csv_parser_first_final int = 8
const csv_parser_error int = 0

const csv_parser_en_main int = 8


//.... lightning/mydump/csv_parser.rl:60

func (parser *CSVParser) lex() (csvToken, []byte, error) {
	var delim byte
	if len(parser.cfg.Delimiter) > 0 {
		delim = parser.cfg.Delimiter[0]
	}
	sep := parser.cfg.Separator[0]

	var cs, ts, te, act, p int
	
//.... tmp_parser.go:43
	{
	cs = csv_parser_start
	ts = 0
	te = 0
	act = 0
	}

//.... lightning/mydump/csv_parser.rl:70

	for {
		data := parser.buf
		consumedToken := csvTokNil
		pe := len(data)
		eof := -1
		if parser.isLastChunk {
			eof = pe
		}

		
//.... tmp_parser.go:63
	{
	var _widec int16
	if p == pe {
		goto _test_eof
	}
	switch cs {
	case 8:
		goto st_case_8
	case 0:
		goto st_case_0
	case 9:
		goto st_case_9
	case 10:
		goto st_case_10
	case 1:
		goto st_case_1
	case 2:
		goto st_case_2
	case 11:
		goto st_case_11
	case 12:
		goto st_case_12
	case 3:
		goto st_case_3
	case 13:
		goto st_case_13
	case 4:
		goto st_case_4
	case 14:
		goto st_case_14
	case 15:
		goto st_case_15
	case 5:
		goto st_case_5
	case 16:
		goto st_case_16
	case 6:
		goto st_case_6
	case 17:
		goto st_case_17
	case 7:
		goto st_case_7
	case 18:
		goto st_case_18
	case 19:
		goto st_case_19
	case 20:
		goto st_case_20
	case 21:
		goto st_case_21
	case 22:
		goto st_case_22
	case 23:
		goto st_case_23
	case 24:
		goto st_case_24
	}
	goto st_out
tr0:
//.... NONE:1
	switch act {
	case 0:
	{{goto st0 }}
	case 1:
	{p = (te) - 1

		consumedToken = csvTokSep
		{p++; cs = 8; goto _out }
	}
	case 2:
	{p = (te) - 1

		consumedToken = csvTokField
		{p++; cs = 8; goto _out }
	}
	}
	
	goto st8
tr14:
//.... lightning/mydump/csv_parser.rl:45
p = (te) - 1
{
		consumedToken = csvTokField
		{p++; cs = 8; goto _out }
	}
	goto st8
tr17:
//.... lightning/mydump/csv_parser.rl:40
te = p+1
{
		consumedToken = csvTokSep
		{p++; cs = 8; goto _out }
	}
	goto st8
tr23:
//.... lightning/mydump/csv_parser.rl:50
te = p
p--
{
		consumedToken = csvTokNewLine
		{p++; cs = 8; goto _out }
	}
	goto st8
tr24:
//.... lightning/mydump/csv_parser.rl:45
te = p
p--
{
		consumedToken = csvTokField
		{p++; cs = 8; goto _out }
	}
	goto st8
tr25:
//.... lightning/mydump/csv_parser.rl:40
te = p
p--
{
		consumedToken = csvTokSep
		{p++; cs = 8; goto _out }
	}
	goto st8
	st8:
//.... NONE:1
ts = 0

//.... NONE:1
act = 0

		if p++; p == pe {
			goto _test_eof8
		}
	st_case_8:
//.... NONE:1
ts = p

//.... tmp_parser.go:199
		_widec = int16(data[p])
		switch {
		case data[p] < 14:
			switch {
			case data[p] > 9:
				if 11 <= data[p] && data[p] <= 12 {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			default:
				_widec = 2816 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  data[p] == sep  {
					_widec += 512
				}
			}
		case data[p] > 91:
			switch {
			case data[p] > 92:
				if 93 <= data[p] {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			case data[p] >= 92:
				_widec = 3840 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  parser.escFlavor != backslashEscapeFlavorNone  {
					_widec += 512
				}
				if  data[p] == sep  {
					_widec += 1024
				}
			}
		default:
			_widec = 2816 + (int16(data[p]) - 0)
			if  data[p] == delim  {
				_widec += 256
			}
			if  data[p] == sep  {
				_widec += 512
			}
		}
		switch _widec {
		case 10:
			goto st9
		case 13:
			goto st9
		case 3932:
			goto tr1
		case 4188:
			goto st2
		case 4444:
			goto st1
		case 4700:
			goto st5
		case 4956:
			goto tr17
		case 5212:
			goto tr18
		case 5468:
			goto st23
		case 5724:
			goto st24
		}
		switch {
		case _widec < 3165:
			switch {
			case _widec < 2909:
				switch {
				case _widec < 2827:
					if 2816 <= _widec && _widec <= 2825 {
						goto tr1
					}
				case _widec > 2828:
					if 2830 <= _widec && _widec <= 2907 {
						goto tr1
					}
				default:
					goto tr1
				}
			case _widec > 3071:
				switch {
				case _widec < 3083:
					if 3072 <= _widec && _widec <= 3081 {
						goto st2
					}
				case _widec > 3084:
					if 3086 <= _widec && _widec <= 3163 {
						goto st2
					}
				default:
					goto st2
				}
			default:
				goto tr1
			}
		case _widec > 3327:
			switch {
			case _widec < 3421:
				switch {
				case _widec < 3339:
					if 3328 <= _widec && _widec <= 3337 {
						goto tr17
					}
				case _widec > 3340:
					if 3342 <= _widec && _widec <= 3419 {
						goto tr17
					}
				default:
					goto tr17
				}
			case _widec > 3583:
				switch {
				case _widec < 3595:
					if 3584 <= _widec && _widec <= 3593 {
						goto tr18
					}
				case _widec > 3596:
					switch {
					case _widec > 3675:
						if 3677 <= _widec && _widec <= 3839 {
							goto tr18
						}
					case _widec >= 3598:
						goto tr18
					}
				default:
					goto tr18
				}
			default:
				goto tr17
			}
		default:
			goto st2
		}
		goto st0
st_case_0:
	st0:
		cs = 0
		goto _out
	st9:
		if p++; p == pe {
			goto _test_eof9
		}
	st_case_9:
		switch data[p] {
		case 10:
			goto st9
		case 13:
			goto st9
		}
		goto tr23
tr1:
//.... NONE:1
te = p+1

//.... lightning/mydump/csv_parser.rl:45
act = 2;
	goto st10
	st10:
		if p++; p == pe {
			goto _test_eof10
		}
	st_case_10:
//.... tmp_parser.go:378
		_widec = int16(data[p])
		switch {
		case data[p] < 14:
			switch {
			case data[p] > 9:
				if 11 <= data[p] && data[p] <= 12 {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			default:
				_widec = 2816 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  data[p] == sep  {
					_widec += 512
				}
			}
		case data[p] > 91:
			switch {
			case data[p] > 92:
				if 93 <= data[p] {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			case data[p] >= 92:
				_widec = 3840 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  parser.escFlavor != backslashEscapeFlavorNone  {
					_widec += 512
				}
				if  data[p] == sep  {
					_widec += 1024
				}
			}
		default:
			_widec = 2816 + (int16(data[p]) - 0)
			if  data[p] == delim  {
				_widec += 256
			}
			if  data[p] == sep  {
				_widec += 512
			}
		}
		switch _widec {
		case 3932:
			goto tr1
		case 4444:
			goto st1
		case 4700:
			goto st1
		case 5468:
			goto st1
		case 5724:
			goto st1
		}
		switch {
		case _widec < 2827:
			if 2816 <= _widec && _widec <= 2825 {
				goto tr1
			}
		case _widec > 2828:
			switch {
			case _widec > 2907:
				if 2909 <= _widec && _widec <= 3071 {
					goto tr1
				}
			case _widec >= 2830:
				goto tr1
			}
		default:
			goto tr1
		}
		goto tr24
	st1:
		if p++; p == pe {
			goto _test_eof1
		}
	st_case_1:
		goto tr1
	st2:
		if p++; p == pe {
			goto _test_eof2
		}
	st_case_2:
		_widec = int16(data[p])
		switch {
		case data[p] < 14:
			switch {
			case data[p] > 9:
				if 11 <= data[p] && data[p] <= 12 {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			default:
				_widec = 2816 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  data[p] == sep  {
					_widec += 512
				}
			}
		case data[p] > 91:
			switch {
			case data[p] > 92:
				if 93 <= data[p] {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			case data[p] >= 92:
				_widec = 3840 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  parser.escFlavor != backslashEscapeFlavorNone  {
					_widec += 512
				}
				if  data[p] == sep  {
					_widec += 1024
				}
			}
		default:
			_widec = 2816 + (int16(data[p]) - 0)
			if  data[p] == delim  {
				_widec += 256
			}
			if  data[p] == sep  {
				_widec += 512
			}
		}
		switch _widec {
		case 10:
			goto st2
		case 13:
			goto st2
		case 3932:
			goto st2
		case 4188:
			goto tr3
		case 4444:
			goto st3
		case 4700:
			goto tr6
		case 4956:
			goto st2
		case 5212:
			goto tr4
		case 5468:
			goto st4
		case 5724:
			goto tr8
		}
		switch {
		case _widec < 3165:
			switch {
			case _widec < 2909:
				switch {
				case _widec < 2827:
					if 2816 <= _widec && _widec <= 2825 {
						goto st2
					}
				case _widec > 2828:
					if 2830 <= _widec && _widec <= 2907 {
						goto st2
					}
				default:
					goto st2
				}
			case _widec > 3071:
				switch {
				case _widec < 3083:
					if 3072 <= _widec && _widec <= 3081 {
						goto tr3
					}
				case _widec > 3084:
					if 3086 <= _widec && _widec <= 3163 {
						goto tr3
					}
				default:
					goto tr3
				}
			default:
				goto st2
			}
		case _widec > 3327:
			switch {
			case _widec < 3421:
				switch {
				case _widec < 3339:
					if 3328 <= _widec && _widec <= 3337 {
						goto st2
					}
				case _widec > 3340:
					if 3342 <= _widec && _widec <= 3419 {
						goto st2
					}
				default:
					goto st2
				}
			case _widec > 3583:
				switch {
				case _widec < 3595:
					if 3584 <= _widec && _widec <= 3593 {
						goto tr4
					}
				case _widec > 3596:
					switch {
					case _widec > 3675:
						if 3677 <= _widec && _widec <= 3839 {
							goto tr4
						}
					case _widec >= 3598:
						goto tr4
					}
				default:
					goto tr4
				}
			default:
				goto st2
			}
		default:
			goto tr3
		}
		goto tr0
tr3:
//.... NONE:1
te = p+1

//.... lightning/mydump/csv_parser.rl:45
act = 2;
	goto st11
	st11:
		if p++; p == pe {
			goto _test_eof11
		}
	st_case_11:
//.... tmp_parser.go:638
		_widec = int16(data[p])
		switch {
		case data[p] < 11:
			if data[p] <= 9 {
				_widec = 768 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
			}
		case data[p] > 12:
			if 14 <= data[p] {
				_widec = 768 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
			}
		default:
			_widec = 768 + (int16(data[p]) - 0)
			if  data[p] == delim  {
				_widec += 256
			}
		}
		switch {
		case _widec < 1035:
			if 1024 <= _widec && _widec <= 1033 {
				goto st2
			}
		case _widec > 1036:
			if 1038 <= _widec && _widec <= 1279 {
				goto st2
			}
		default:
			goto st2
		}
		goto tr24
tr4:
//.... NONE:1
te = p+1

//.... lightning/mydump/csv_parser.rl:45
act = 2;
	goto st12
	st12:
		if p++; p == pe {
			goto _test_eof12
		}
	st_case_12:
//.... tmp_parser.go:686
		_widec = int16(data[p])
		switch {
		case data[p] < 14:
			switch {
			case data[p] > 9:
				if 11 <= data[p] && data[p] <= 12 {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			default:
				_widec = 2816 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  data[p] == sep  {
					_widec += 512
				}
			}
		case data[p] > 91:
			switch {
			case data[p] > 92:
				if 93 <= data[p] {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			case data[p] >= 92:
				_widec = 3840 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  parser.escFlavor != backslashEscapeFlavorNone  {
					_widec += 512
				}
				if  data[p] == sep  {
					_widec += 1024
				}
			}
		default:
			_widec = 2816 + (int16(data[p]) - 0)
			if  data[p] == delim  {
				_widec += 256
			}
			if  data[p] == sep  {
				_widec += 512
			}
		}
		switch _widec {
		case 10:
			goto st2
		case 13:
			goto st2
		case 3932:
			goto st2
		case 4188:
			goto tr4
		case 4444:
			goto st3
		case 4700:
			goto tr8
		case 4956:
			goto st2
		case 5212:
			goto tr4
		case 5468:
			goto st4
		case 5724:
			goto tr8
		}
		switch {
		case _widec < 3165:
			switch {
			case _widec < 2909:
				switch {
				case _widec < 2827:
					if 2816 <= _widec && _widec <= 2825 {
						goto st2
					}
				case _widec > 2828:
					if 2830 <= _widec && _widec <= 2907 {
						goto st2
					}
				default:
					goto st2
				}
			case _widec > 3071:
				switch {
				case _widec < 3083:
					if 3072 <= _widec && _widec <= 3081 {
						goto tr4
					}
				case _widec > 3084:
					if 3086 <= _widec && _widec <= 3163 {
						goto tr4
					}
				default:
					goto tr4
				}
			default:
				goto st2
			}
		case _widec > 3327:
			switch {
			case _widec < 3421:
				switch {
				case _widec < 3339:
					if 3328 <= _widec && _widec <= 3337 {
						goto st2
					}
				case _widec > 3340:
					if 3342 <= _widec && _widec <= 3419 {
						goto st2
					}
				default:
					goto st2
				}
			case _widec > 3583:
				switch {
				case _widec < 3595:
					if 3584 <= _widec && _widec <= 3593 {
						goto tr4
					}
				case _widec > 3596:
					switch {
					case _widec > 3675:
						if 3677 <= _widec && _widec <= 3839 {
							goto tr4
						}
					case _widec >= 3598:
						goto tr4
					}
				default:
					goto tr4
				}
			default:
				goto st2
			}
		default:
			goto tr4
		}
		goto tr24
	st3:
		if p++; p == pe {
			goto _test_eof3
		}
	st_case_3:
		goto st2
tr8:
//.... NONE:1
te = p+1

//.... lightning/mydump/csv_parser.rl:45
act = 2;
	goto st13
	st13:
		if p++; p == pe {
			goto _test_eof13
		}
	st_case_13:
//.... tmp_parser.go:855
		_widec = int16(data[p])
		switch {
		case data[p] < 14:
			switch {
			case data[p] > 9:
				if 11 <= data[p] && data[p] <= 12 {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			default:
				_widec = 2816 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  data[p] == sep  {
					_widec += 512
				}
			}
		case data[p] > 91:
			switch {
			case data[p] > 92:
				if 93 <= data[p] {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			case data[p] >= 92:
				_widec = 3840 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  parser.escFlavor != backslashEscapeFlavorNone  {
					_widec += 512
				}
				if  data[p] == sep  {
					_widec += 1024
				}
			}
		default:
			_widec = 2816 + (int16(data[p]) - 0)
			if  data[p] == delim  {
				_widec += 256
			}
			if  data[p] == sep  {
				_widec += 512
			}
		}
		switch _widec {
		case 10:
			goto st2
		case 13:
			goto st2
		case 3932:
			goto st2
		case 4188:
			goto tr4
		case 4444:
			goto st4
		case 4700:
			goto tr8
		case 4956:
			goto st2
		case 5212:
			goto tr4
		case 5468:
			goto st4
		case 5724:
			goto tr8
		}
		switch {
		case _widec < 3165:
			switch {
			case _widec < 2909:
				switch {
				case _widec < 2827:
					if 2816 <= _widec && _widec <= 2825 {
						goto st2
					}
				case _widec > 2828:
					if 2830 <= _widec && _widec <= 2907 {
						goto st2
					}
				default:
					goto st2
				}
			case _widec > 3071:
				switch {
				case _widec < 3083:
					if 3072 <= _widec && _widec <= 3081 {
						goto tr4
					}
				case _widec > 3084:
					if 3086 <= _widec && _widec <= 3163 {
						goto tr4
					}
				default:
					goto tr4
				}
			default:
				goto st2
			}
		case _widec > 3327:
			switch {
			case _widec < 3421:
				switch {
				case _widec < 3339:
					if 3328 <= _widec && _widec <= 3337 {
						goto st2
					}
				case _widec > 3340:
					if 3342 <= _widec && _widec <= 3419 {
						goto st2
					}
				default:
					goto st2
				}
			case _widec > 3583:
				switch {
				case _widec < 3595:
					if 3584 <= _widec && _widec <= 3593 {
						goto tr4
					}
				case _widec > 3596:
					switch {
					case _widec > 3675:
						if 3677 <= _widec && _widec <= 3839 {
							goto tr4
						}
					case _widec >= 3598:
						goto tr4
					}
				default:
					goto tr4
				}
			default:
				goto st2
			}
		default:
			goto tr4
		}
		goto tr24
	st4:
		if p++; p == pe {
			goto _test_eof4
		}
	st_case_4:
		_widec = int16(data[p])
		switch {
		case data[p] < 14:
			switch {
			case data[p] > 9:
				if 11 <= data[p] && data[p] <= 12 {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			default:
				_widec = 2816 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  data[p] == sep  {
					_widec += 512
				}
			}
		case data[p] > 91:
			switch {
			case data[p] > 92:
				if 93 <= data[p] {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			case data[p] >= 92:
				_widec = 3840 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  parser.escFlavor != backslashEscapeFlavorNone  {
					_widec += 512
				}
				if  data[p] == sep  {
					_widec += 1024
				}
			}
		default:
			_widec = 2816 + (int16(data[p]) - 0)
			if  data[p] == delim  {
				_widec += 256
			}
			if  data[p] == sep  {
				_widec += 512
			}
		}
		switch _widec {
		case 10:
			goto st2
		case 13:
			goto st2
		case 3932:
			goto st2
		case 4188:
			goto tr4
		case 4444:
			goto st4
		case 4700:
			goto tr8
		case 4956:
			goto st2
		case 5212:
			goto tr4
		case 5468:
			goto st4
		case 5724:
			goto tr8
		}
		switch {
		case _widec < 3165:
			switch {
			case _widec < 2909:
				switch {
				case _widec < 2827:
					if 2816 <= _widec && _widec <= 2825 {
						goto st2
					}
				case _widec > 2828:
					if 2830 <= _widec && _widec <= 2907 {
						goto st2
					}
				default:
					goto st2
				}
			case _widec > 3071:
				switch {
				case _widec < 3083:
					if 3072 <= _widec && _widec <= 3081 {
						goto tr4
					}
				case _widec > 3084:
					if 3086 <= _widec && _widec <= 3163 {
						goto tr4
					}
				default:
					goto tr4
				}
			default:
				goto st2
			}
		case _widec > 3327:
			switch {
			case _widec < 3421:
				switch {
				case _widec < 3339:
					if 3328 <= _widec && _widec <= 3337 {
						goto st2
					}
				case _widec > 3340:
					if 3342 <= _widec && _widec <= 3419 {
						goto st2
					}
				default:
					goto st2
				}
			case _widec > 3583:
				switch {
				case _widec < 3595:
					if 3584 <= _widec && _widec <= 3593 {
						goto tr4
					}
				case _widec > 3596:
					switch {
					case _widec > 3675:
						if 3677 <= _widec && _widec <= 3839 {
							goto tr4
						}
					case _widec >= 3598:
						goto tr4
					}
				default:
					goto tr4
				}
			default:
				goto st2
			}
		default:
			goto tr4
		}
		goto tr0
tr6:
//.... NONE:1
te = p+1

//.... lightning/mydump/csv_parser.rl:45
act = 2;
	goto st14
	st14:
		if p++; p == pe {
			goto _test_eof14
		}
	st_case_14:
//.... tmp_parser.go:1173
		_widec = int16(data[p])
		switch {
		case data[p] < 11:
			if data[p] <= 9 {
				_widec = 768 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
			}
		case data[p] > 12:
			if 14 <= data[p] {
				_widec = 768 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
			}
		default:
			_widec = 768 + (int16(data[p]) - 0)
			if  data[p] == delim  {
				_widec += 256
			}
		}
		switch _widec {
		case 10:
			goto st2
		case 13:
			goto st2
		}
		switch {
		case _widec < 782:
			switch {
			case _widec > 777:
				if 779 <= _widec && _widec <= 780 {
					goto st2
				}
			case _widec >= 768:
				goto st2
			}
		case _widec > 1033:
			switch {
			case _widec > 1036:
				if 1038 <= _widec && _widec <= 1279 {
					goto st2
				}
			case _widec >= 1035:
				goto st2
			}
		default:
			goto st2
		}
		goto tr24
tr18:
//.... NONE:1
te = p+1

//.... lightning/mydump/csv_parser.rl:40
act = 1;
	goto st15
	st15:
		if p++; p == pe {
			goto _test_eof15
		}
	st_case_15:
//.... tmp_parser.go:1237
		_widec = int16(data[p])
		switch {
		case data[p] < 14:
			switch {
			case data[p] > 9:
				if 11 <= data[p] && data[p] <= 12 {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			default:
				_widec = 2816 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  data[p] == sep  {
					_widec += 512
				}
			}
		case data[p] > 91:
			switch {
			case data[p] > 92:
				if 93 <= data[p] {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			case data[p] >= 92:
				_widec = 3840 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  parser.escFlavor != backslashEscapeFlavorNone  {
					_widec += 512
				}
				if  data[p] == sep  {
					_widec += 1024
				}
			}
		default:
			_widec = 2816 + (int16(data[p]) - 0)
			if  data[p] == delim  {
				_widec += 256
			}
			if  data[p] == sep  {
				_widec += 512
			}
		}
		switch _widec {
		case 10:
			goto st2
		case 13:
			goto st2
		case 3932:
			goto st2
		case 4188:
			goto tr3
		case 4444:
			goto st3
		case 4700:
			goto tr6
		case 4956:
			goto st2
		case 5212:
			goto tr4
		case 5468:
			goto st4
		case 5724:
			goto tr8
		}
		switch {
		case _widec < 3165:
			switch {
			case _widec < 2909:
				switch {
				case _widec < 2827:
					if 2816 <= _widec && _widec <= 2825 {
						goto st2
					}
				case _widec > 2828:
					if 2830 <= _widec && _widec <= 2907 {
						goto st2
					}
				default:
					goto st2
				}
			case _widec > 3071:
				switch {
				case _widec < 3083:
					if 3072 <= _widec && _widec <= 3081 {
						goto tr3
					}
				case _widec > 3084:
					if 3086 <= _widec && _widec <= 3163 {
						goto tr3
					}
				default:
					goto tr3
				}
			default:
				goto st2
			}
		case _widec > 3327:
			switch {
			case _widec < 3421:
				switch {
				case _widec < 3339:
					if 3328 <= _widec && _widec <= 3337 {
						goto st2
					}
				case _widec > 3340:
					if 3342 <= _widec && _widec <= 3419 {
						goto st2
					}
				default:
					goto st2
				}
			case _widec > 3583:
				switch {
				case _widec < 3595:
					if 3584 <= _widec && _widec <= 3593 {
						goto tr4
					}
				case _widec > 3596:
					switch {
					case _widec > 3675:
						if 3677 <= _widec && _widec <= 3839 {
							goto tr4
						}
					case _widec >= 3598:
						goto tr4
					}
				default:
					goto tr4
				}
			default:
				goto st2
			}
		default:
			goto tr3
		}
		goto tr25
	st5:
		if p++; p == pe {
			goto _test_eof5
		}
	st_case_5:
		_widec = int16(data[p])
		switch {
		case data[p] < 14:
			switch {
			case data[p] > 9:
				if 11 <= data[p] && data[p] <= 12 {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			default:
				_widec = 2816 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  data[p] == sep  {
					_widec += 512
				}
			}
		case data[p] > 91:
			switch {
			case data[p] > 92:
				if 93 <= data[p] {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			case data[p] >= 92:
				_widec = 3840 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  parser.escFlavor != backslashEscapeFlavorNone  {
					_widec += 512
				}
				if  data[p] == sep  {
					_widec += 1024
				}
			}
		default:
			_widec = 2816 + (int16(data[p]) - 0)
			if  data[p] == delim  {
				_widec += 256
			}
			if  data[p] == sep  {
				_widec += 512
			}
		}
		switch _widec {
		case 10:
			goto tr9
		case 13:
			goto tr9
		case 3932:
			goto tr9
		case 4188:
			goto tr10
		case 4444:
			goto tr12
		case 4700:
			goto tr12
		case 4956:
			goto tr9
		case 5212:
			goto tr11
		case 5468:
			goto tr13
		case 5724:
			goto tr13
		}
		switch {
		case _widec < 3165:
			switch {
			case _widec < 2909:
				switch {
				case _widec < 2827:
					if 2816 <= _widec && _widec <= 2825 {
						goto tr9
					}
				case _widec > 2828:
					if 2830 <= _widec && _widec <= 2907 {
						goto tr9
					}
				default:
					goto tr9
				}
			case _widec > 3071:
				switch {
				case _widec < 3083:
					if 3072 <= _widec && _widec <= 3081 {
						goto tr10
					}
				case _widec > 3084:
					if 3086 <= _widec && _widec <= 3163 {
						goto tr10
					}
				default:
					goto tr10
				}
			default:
				goto tr9
			}
		case _widec > 3327:
			switch {
			case _widec < 3421:
				switch {
				case _widec < 3339:
					if 3328 <= _widec && _widec <= 3337 {
						goto tr9
					}
				case _widec > 3340:
					if 3342 <= _widec && _widec <= 3419 {
						goto tr9
					}
				default:
					goto tr9
				}
			case _widec > 3583:
				switch {
				case _widec < 3595:
					if 3584 <= _widec && _widec <= 3593 {
						goto tr11
					}
				case _widec > 3596:
					switch {
					case _widec > 3675:
						if 3677 <= _widec && _widec <= 3839 {
							goto tr11
						}
					case _widec >= 3598:
						goto tr11
					}
				default:
					goto tr11
				}
			default:
				goto tr9
			}
		default:
			goto tr10
		}
		goto tr0
tr9:
//.... NONE:1
te = p+1

//.... lightning/mydump/csv_parser.rl:45
act = 2;
	goto st16
	st16:
		if p++; p == pe {
			goto _test_eof16
		}
	st_case_16:
//.... tmp_parser.go:1555
		_widec = int16(data[p])
		switch {
		case data[p] < 14:
			switch {
			case data[p] > 9:
				if 11 <= data[p] && data[p] <= 12 {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			default:
				_widec = 2816 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  data[p] == sep  {
					_widec += 512
				}
			}
		case data[p] > 91:
			switch {
			case data[p] > 92:
				if 93 <= data[p] {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			case data[p] >= 92:
				_widec = 3840 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  parser.escFlavor != backslashEscapeFlavorNone  {
					_widec += 512
				}
				if  data[p] == sep  {
					_widec += 1024
				}
			}
		default:
			_widec = 2816 + (int16(data[p]) - 0)
			if  data[p] == delim  {
				_widec += 256
			}
			if  data[p] == sep  {
				_widec += 512
			}
		}
		switch _widec {
		case 10:
			goto st2
		case 13:
			goto st2
		case 3932:
			goto tr9
		case 4188:
			goto tr3
		case 4444:
			goto st6
		case 4700:
			goto st17
		case 4956:
			goto st2
		case 5212:
			goto tr4
		case 5468:
			goto st7
		case 5724:
			goto st19
		}
		switch {
		case _widec < 3165:
			switch {
			case _widec < 2909:
				switch {
				case _widec < 2827:
					if 2816 <= _widec && _widec <= 2825 {
						goto tr9
					}
				case _widec > 2828:
					if 2830 <= _widec && _widec <= 2907 {
						goto tr9
					}
				default:
					goto tr9
				}
			case _widec > 3071:
				switch {
				case _widec < 3083:
					if 3072 <= _widec && _widec <= 3081 {
						goto tr3
					}
				case _widec > 3084:
					if 3086 <= _widec && _widec <= 3163 {
						goto tr3
					}
				default:
					goto tr3
				}
			default:
				goto tr9
			}
		case _widec > 3327:
			switch {
			case _widec < 3421:
				switch {
				case _widec < 3339:
					if 3328 <= _widec && _widec <= 3337 {
						goto st2
					}
				case _widec > 3340:
					if 3342 <= _widec && _widec <= 3419 {
						goto st2
					}
				default:
					goto st2
				}
			case _widec > 3583:
				switch {
				case _widec < 3595:
					if 3584 <= _widec && _widec <= 3593 {
						goto tr4
					}
				case _widec > 3596:
					switch {
					case _widec > 3675:
						if 3677 <= _widec && _widec <= 3839 {
							goto tr4
						}
					case _widec >= 3598:
						goto tr4
					}
				default:
					goto tr4
				}
			default:
				goto st2
			}
		default:
			goto tr3
		}
		goto tr24
	st6:
		if p++; p == pe {
			goto _test_eof6
		}
	st_case_6:
		goto tr9
	st17:
		if p++; p == pe {
			goto _test_eof17
		}
	st_case_17:
		_widec = int16(data[p])
		switch {
		case data[p] < 11:
			if data[p] <= 9 {
				_widec = 768 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
			}
		case data[p] > 12:
			if 14 <= data[p] {
				_widec = 768 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
			}
		default:
			_widec = 768 + (int16(data[p]) - 0)
			if  data[p] == delim  {
				_widec += 256
			}
		}
		switch _widec {
		case 10:
			goto tr9
		case 13:
			goto tr9
		}
		switch {
		case _widec < 782:
			switch {
			case _widec > 777:
				if 779 <= _widec && _widec <= 780 {
					goto tr9
				}
			case _widec >= 768:
				goto tr9
			}
		case _widec > 1033:
			switch {
			case _widec > 1036:
				if 1038 <= _widec && _widec <= 1279 {
					goto tr9
				}
			case _widec >= 1035:
				goto tr9
			}
		default:
			goto tr9
		}
		goto tr24
	st7:
		if p++; p == pe {
			goto _test_eof7
		}
	st_case_7:
		_widec = int16(data[p])
		switch {
		case data[p] < 14:
			switch {
			case data[p] > 9:
				if 11 <= data[p] && data[p] <= 12 {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			default:
				_widec = 2816 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  data[p] == sep  {
					_widec += 512
				}
			}
		case data[p] > 91:
			switch {
			case data[p] > 92:
				if 93 <= data[p] {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			case data[p] >= 92:
				_widec = 3840 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  parser.escFlavor != backslashEscapeFlavorNone  {
					_widec += 512
				}
				if  data[p] == sep  {
					_widec += 1024
				}
			}
		default:
			_widec = 2816 + (int16(data[p]) - 0)
			if  data[p] == delim  {
				_widec += 256
			}
			if  data[p] == sep  {
				_widec += 512
			}
		}
		switch _widec {
		case 10:
			goto tr9
		case 13:
			goto tr9
		case 3932:
			goto tr9
		case 4188:
			goto tr11
		case 4444:
			goto tr13
		case 4700:
			goto tr13
		case 4956:
			goto tr9
		case 5212:
			goto tr11
		case 5468:
			goto tr13
		case 5724:
			goto tr13
		}
		switch {
		case _widec < 3165:
			switch {
			case _widec < 2909:
				switch {
				case _widec < 2827:
					if 2816 <= _widec && _widec <= 2825 {
						goto tr9
					}
				case _widec > 2828:
					if 2830 <= _widec && _widec <= 2907 {
						goto tr9
					}
				default:
					goto tr9
				}
			case _widec > 3071:
				switch {
				case _widec < 3083:
					if 3072 <= _widec && _widec <= 3081 {
						goto tr11
					}
				case _widec > 3084:
					if 3086 <= _widec && _widec <= 3163 {
						goto tr11
					}
				default:
					goto tr11
				}
			default:
				goto tr9
			}
		case _widec > 3327:
			switch {
			case _widec < 3421:
				switch {
				case _widec < 3339:
					if 3328 <= _widec && _widec <= 3337 {
						goto tr9
					}
				case _widec > 3340:
					if 3342 <= _widec && _widec <= 3419 {
						goto tr9
					}
				default:
					goto tr9
				}
			case _widec > 3583:
				switch {
				case _widec < 3595:
					if 3584 <= _widec && _widec <= 3593 {
						goto tr11
					}
				case _widec > 3596:
					switch {
					case _widec > 3675:
						if 3677 <= _widec && _widec <= 3839 {
							goto tr11
						}
					case _widec >= 3598:
						goto tr11
					}
				default:
					goto tr11
				}
			default:
				goto tr9
			}
		default:
			goto tr11
		}
		goto tr14
tr11:
//.... NONE:1
te = p+1

//.... lightning/mydump/csv_parser.rl:45
act = 2;
	goto st18
	st18:
		if p++; p == pe {
			goto _test_eof18
		}
	st_case_18:
//.... tmp_parser.go:1935
		_widec = int16(data[p])
		switch {
		case data[p] < 14:
			switch {
			case data[p] > 9:
				if 11 <= data[p] && data[p] <= 12 {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			default:
				_widec = 2816 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  data[p] == sep  {
					_widec += 512
				}
			}
		case data[p] > 91:
			switch {
			case data[p] > 92:
				if 93 <= data[p] {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			case data[p] >= 92:
				_widec = 3840 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  parser.escFlavor != backslashEscapeFlavorNone  {
					_widec += 512
				}
				if  data[p] == sep  {
					_widec += 1024
				}
			}
		default:
			_widec = 2816 + (int16(data[p]) - 0)
			if  data[p] == delim  {
				_widec += 256
			}
			if  data[p] == sep  {
				_widec += 512
			}
		}
		switch _widec {
		case 10:
			goto st2
		case 13:
			goto st2
		case 3932:
			goto tr9
		case 4188:
			goto tr4
		case 4444:
			goto st6
		case 4700:
			goto st19
		case 4956:
			goto st2
		case 5212:
			goto tr4
		case 5468:
			goto st7
		case 5724:
			goto st19
		}
		switch {
		case _widec < 3165:
			switch {
			case _widec < 2909:
				switch {
				case _widec < 2827:
					if 2816 <= _widec && _widec <= 2825 {
						goto tr9
					}
				case _widec > 2828:
					if 2830 <= _widec && _widec <= 2907 {
						goto tr9
					}
				default:
					goto tr9
				}
			case _widec > 3071:
				switch {
				case _widec < 3083:
					if 3072 <= _widec && _widec <= 3081 {
						goto tr4
					}
				case _widec > 3084:
					if 3086 <= _widec && _widec <= 3163 {
						goto tr4
					}
				default:
					goto tr4
				}
			default:
				goto tr9
			}
		case _widec > 3327:
			switch {
			case _widec < 3421:
				switch {
				case _widec < 3339:
					if 3328 <= _widec && _widec <= 3337 {
						goto st2
					}
				case _widec > 3340:
					if 3342 <= _widec && _widec <= 3419 {
						goto st2
					}
				default:
					goto st2
				}
			case _widec > 3583:
				switch {
				case _widec < 3595:
					if 3584 <= _widec && _widec <= 3593 {
						goto tr4
					}
				case _widec > 3596:
					switch {
					case _widec > 3675:
						if 3677 <= _widec && _widec <= 3839 {
							goto tr4
						}
					case _widec >= 3598:
						goto tr4
					}
				default:
					goto tr4
				}
			default:
				goto st2
			}
		default:
			goto tr4
		}
		goto tr24
	st19:
		if p++; p == pe {
			goto _test_eof19
		}
	st_case_19:
		_widec = int16(data[p])
		switch {
		case data[p] < 14:
			switch {
			case data[p] > 9:
				if 11 <= data[p] && data[p] <= 12 {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			default:
				_widec = 2816 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  data[p] == sep  {
					_widec += 512
				}
			}
		case data[p] > 91:
			switch {
			case data[p] > 92:
				if 93 <= data[p] {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			case data[p] >= 92:
				_widec = 3840 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  parser.escFlavor != backslashEscapeFlavorNone  {
					_widec += 512
				}
				if  data[p] == sep  {
					_widec += 1024
				}
			}
		default:
			_widec = 2816 + (int16(data[p]) - 0)
			if  data[p] == delim  {
				_widec += 256
			}
			if  data[p] == sep  {
				_widec += 512
			}
		}
		switch _widec {
		case 10:
			goto tr9
		case 13:
			goto tr9
		case 3932:
			goto tr9
		case 4188:
			goto tr11
		case 4444:
			goto tr13
		case 4700:
			goto tr13
		case 4956:
			goto tr9
		case 5212:
			goto tr11
		case 5468:
			goto tr13
		case 5724:
			goto tr13
		}
		switch {
		case _widec < 3165:
			switch {
			case _widec < 2909:
				switch {
				case _widec < 2827:
					if 2816 <= _widec && _widec <= 2825 {
						goto tr9
					}
				case _widec > 2828:
					if 2830 <= _widec && _widec <= 2907 {
						goto tr9
					}
				default:
					goto tr9
				}
			case _widec > 3071:
				switch {
				case _widec < 3083:
					if 3072 <= _widec && _widec <= 3081 {
						goto tr11
					}
				case _widec > 3084:
					if 3086 <= _widec && _widec <= 3163 {
						goto tr11
					}
				default:
					goto tr11
				}
			default:
				goto tr9
			}
		case _widec > 3327:
			switch {
			case _widec < 3421:
				switch {
				case _widec < 3339:
					if 3328 <= _widec && _widec <= 3337 {
						goto tr9
					}
				case _widec > 3340:
					if 3342 <= _widec && _widec <= 3419 {
						goto tr9
					}
				default:
					goto tr9
				}
			case _widec > 3583:
				switch {
				case _widec < 3595:
					if 3584 <= _widec && _widec <= 3593 {
						goto tr11
					}
				case _widec > 3596:
					switch {
					case _widec > 3675:
						if 3677 <= _widec && _widec <= 3839 {
							goto tr11
						}
					case _widec >= 3598:
						goto tr11
					}
				default:
					goto tr11
				}
			default:
				goto tr9
			}
		default:
			goto tr11
		}
		goto tr24
tr13:
//.... NONE:1
te = p+1

//.... lightning/mydump/csv_parser.rl:45
act = 2;
	goto st20
	st20:
		if p++; p == pe {
			goto _test_eof20
		}
	st_case_20:
//.... tmp_parser.go:2253
		_widec = int16(data[p])
		switch {
		case data[p] < 14:
			switch {
			case data[p] > 9:
				if 11 <= data[p] && data[p] <= 12 {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			default:
				_widec = 2816 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  data[p] == sep  {
					_widec += 512
				}
			}
		case data[p] > 91:
			switch {
			case data[p] > 92:
				if 93 <= data[p] {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			case data[p] >= 92:
				_widec = 3840 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  parser.escFlavor != backslashEscapeFlavorNone  {
					_widec += 512
				}
				if  data[p] == sep  {
					_widec += 1024
				}
			}
		default:
			_widec = 2816 + (int16(data[p]) - 0)
			if  data[p] == delim  {
				_widec += 256
			}
			if  data[p] == sep  {
				_widec += 512
			}
		}
		switch _widec {
		case 10:
			goto st2
		case 13:
			goto st2
		case 3932:
			goto tr9
		case 4188:
			goto tr4
		case 4444:
			goto st7
		case 4700:
			goto st19
		case 4956:
			goto st2
		case 5212:
			goto tr4
		case 5468:
			goto st7
		case 5724:
			goto st19
		}
		switch {
		case _widec < 3165:
			switch {
			case _widec < 2909:
				switch {
				case _widec < 2827:
					if 2816 <= _widec && _widec <= 2825 {
						goto tr9
					}
				case _widec > 2828:
					if 2830 <= _widec && _widec <= 2907 {
						goto tr9
					}
				default:
					goto tr9
				}
			case _widec > 3071:
				switch {
				case _widec < 3083:
					if 3072 <= _widec && _widec <= 3081 {
						goto tr4
					}
				case _widec > 3084:
					if 3086 <= _widec && _widec <= 3163 {
						goto tr4
					}
				default:
					goto tr4
				}
			default:
				goto tr9
			}
		case _widec > 3327:
			switch {
			case _widec < 3421:
				switch {
				case _widec < 3339:
					if 3328 <= _widec && _widec <= 3337 {
						goto st2
					}
				case _widec > 3340:
					if 3342 <= _widec && _widec <= 3419 {
						goto st2
					}
				default:
					goto st2
				}
			case _widec > 3583:
				switch {
				case _widec < 3595:
					if 3584 <= _widec && _widec <= 3593 {
						goto tr4
					}
				case _widec > 3596:
					switch {
					case _widec > 3675:
						if 3677 <= _widec && _widec <= 3839 {
							goto tr4
						}
					case _widec >= 3598:
						goto tr4
					}
				default:
					goto tr4
				}
			default:
				goto st2
			}
		default:
			goto tr4
		}
		goto tr24
tr10:
//.... NONE:1
te = p+1

//.... lightning/mydump/csv_parser.rl:45
act = 2;
	goto st21
	st21:
		if p++; p == pe {
			goto _test_eof21
		}
	st_case_21:
//.... tmp_parser.go:2416
		_widec = int16(data[p])
		switch {
		case data[p] < 14:
			switch {
			case data[p] > 9:
				if 11 <= data[p] && data[p] <= 12 {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			default:
				_widec = 2816 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  data[p] == sep  {
					_widec += 512
				}
			}
		case data[p] > 91:
			switch {
			case data[p] > 92:
				if 93 <= data[p] {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			case data[p] >= 92:
				_widec = 3840 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  parser.escFlavor != backslashEscapeFlavorNone  {
					_widec += 512
				}
				if  data[p] == sep  {
					_widec += 1024
				}
			}
		default:
			_widec = 2816 + (int16(data[p]) - 0)
			if  data[p] == delim  {
				_widec += 256
			}
			if  data[p] == sep  {
				_widec += 512
			}
		}
		switch _widec {
		case 3932:
			goto tr1
		case 4188:
			goto st2
		case 4444:
			goto st1
		case 4700:
			goto st5
		case 5212:
			goto st2
		case 5468:
			goto st1
		case 5724:
			goto st5
		}
		switch {
		case _widec < 3083:
			switch {
			case _widec < 2830:
				switch {
				case _widec > 2825:
					if 2827 <= _widec && _widec <= 2828 {
						goto tr1
					}
				case _widec >= 2816:
					goto tr1
				}
			case _widec > 2907:
				switch {
				case _widec > 3071:
					if 3072 <= _widec && _widec <= 3081 {
						goto st2
					}
				case _widec >= 2909:
					goto tr1
				}
			default:
				goto tr1
			}
		case _widec > 3084:
			switch {
			case _widec < 3584:
				switch {
				case _widec > 3163:
					if 3165 <= _widec && _widec <= 3327 {
						goto st2
					}
				case _widec >= 3086:
					goto st2
				}
			case _widec > 3593:
				switch {
				case _widec < 3598:
					if 3595 <= _widec && _widec <= 3596 {
						goto st2
					}
				case _widec > 3675:
					if 3677 <= _widec && _widec <= 3839 {
						goto st2
					}
				default:
					goto st2
				}
			default:
				goto st2
			}
		default:
			goto st2
		}
		goto tr24
tr12:
//.... NONE:1
te = p+1

//.... lightning/mydump/csv_parser.rl:45
act = 2;
	goto st22
	st22:
		if p++; p == pe {
			goto _test_eof22
		}
	st_case_22:
//.... tmp_parser.go:2556
		_widec = int16(data[p])
		switch {
		case data[p] < 14:
			switch {
			case data[p] > 9:
				if 11 <= data[p] && data[p] <= 12 {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			default:
				_widec = 2816 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  data[p] == sep  {
					_widec += 512
				}
			}
		case data[p] > 91:
			switch {
			case data[p] > 92:
				if 93 <= data[p] {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			case data[p] >= 92:
				_widec = 3840 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  parser.escFlavor != backslashEscapeFlavorNone  {
					_widec += 512
				}
				if  data[p] == sep  {
					_widec += 1024
				}
			}
		default:
			_widec = 2816 + (int16(data[p]) - 0)
			if  data[p] == delim  {
				_widec += 256
			}
			if  data[p] == sep  {
				_widec += 512
			}
		}
		switch _widec {
		case 10:
			goto st2
		case 13:
			goto st2
		case 3932:
			goto tr9
		case 4188:
			goto st2
		case 4444:
			goto st5
		case 4700:
			goto st5
		case 4956:
			goto st2
		case 5212:
			goto st2
		case 5468:
			goto st5
		case 5724:
			goto st5
		}
		switch {
		case _widec < 3086:
			switch {
			case _widec < 2830:
				switch {
				case _widec > 2825:
					if 2827 <= _widec && _widec <= 2828 {
						goto tr9
					}
				case _widec >= 2816:
					goto tr9
				}
			case _widec > 2907:
				switch {
				case _widec < 3072:
					if 2909 <= _widec && _widec <= 3071 {
						goto tr9
					}
				case _widec > 3081:
					if 3083 <= _widec && _widec <= 3084 {
						goto st2
					}
				default:
					goto st2
				}
			default:
				goto tr9
			}
		case _widec > 3163:
			switch {
			case _widec < 3421:
				switch {
				case _widec < 3339:
					if 3165 <= _widec && _widec <= 3337 {
						goto st2
					}
				case _widec > 3340:
					if 3342 <= _widec && _widec <= 3419 {
						goto st2
					}
				default:
					goto st2
				}
			case _widec > 3593:
				switch {
				case _widec < 3598:
					if 3595 <= _widec && _widec <= 3596 {
						goto st2
					}
				case _widec > 3675:
					if 3677 <= _widec && _widec <= 3839 {
						goto st2
					}
				default:
					goto st2
				}
			default:
				goto st2
			}
		default:
			goto st2
		}
		goto tr24
	st23:
		if p++; p == pe {
			goto _test_eof23
		}
	st_case_23:
		goto tr1
	st24:
		if p++; p == pe {
			goto _test_eof24
		}
	st_case_24:
		_widec = int16(data[p])
		switch {
		case data[p] < 14:
			switch {
			case data[p] > 9:
				if 11 <= data[p] && data[p] <= 12 {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			default:
				_widec = 2816 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  data[p] == sep  {
					_widec += 512
				}
			}
		case data[p] > 91:
			switch {
			case data[p] > 92:
				if 93 <= data[p] {
					_widec = 2816 + (int16(data[p]) - 0)
					if  data[p] == delim  {
						_widec += 256
					}
					if  data[p] == sep  {
						_widec += 512
					}
				}
			case data[p] >= 92:
				_widec = 3840 + (int16(data[p]) - 0)
				if  data[p] == delim  {
					_widec += 256
				}
				if  parser.escFlavor != backslashEscapeFlavorNone  {
					_widec += 512
				}
				if  data[p] == sep  {
					_widec += 1024
				}
			}
		default:
			_widec = 2816 + (int16(data[p]) - 0)
			if  data[p] == delim  {
				_widec += 256
			}
			if  data[p] == sep  {
				_widec += 512
			}
		}
		switch _widec {
		case 10:
			goto tr9
		case 13:
			goto tr9
		case 3932:
			goto tr9
		case 4188:
			goto tr10
		case 4444:
			goto tr12
		case 4700:
			goto tr12
		case 4956:
			goto tr9
		case 5212:
			goto tr11
		case 5468:
			goto tr13
		case 5724:
			goto tr13
		}
		switch {
		case _widec < 3165:
			switch {
			case _widec < 2909:
				switch {
				case _widec < 2827:
					if 2816 <= _widec && _widec <= 2825 {
						goto tr9
					}
				case _widec > 2828:
					if 2830 <= _widec && _widec <= 2907 {
						goto tr9
					}
				default:
					goto tr9
				}
			case _widec > 3071:
				switch {
				case _widec < 3083:
					if 3072 <= _widec && _widec <= 3081 {
						goto tr10
					}
				case _widec > 3084:
					if 3086 <= _widec && _widec <= 3163 {
						goto tr10
					}
				default:
					goto tr10
				}
			default:
				goto tr9
			}
		case _widec > 3327:
			switch {
			case _widec < 3421:
				switch {
				case _widec < 3339:
					if 3328 <= _widec && _widec <= 3337 {
						goto tr9
					}
				case _widec > 3340:
					if 3342 <= _widec && _widec <= 3419 {
						goto tr9
					}
				default:
					goto tr9
				}
			case _widec > 3583:
				switch {
				case _widec < 3595:
					if 3584 <= _widec && _widec <= 3593 {
						goto tr11
					}
				case _widec > 3596:
					switch {
					case _widec > 3675:
						if 3677 <= _widec && _widec <= 3839 {
							goto tr11
						}
					case _widec >= 3598:
						goto tr11
					}
				default:
					goto tr11
				}
			default:
				goto tr9
			}
		default:
			goto tr10
		}
		goto tr25
	st_out:
	_test_eof8: cs = 8; goto _test_eof
	_test_eof9: cs = 9; goto _test_eof
	_test_eof10: cs = 10; goto _test_eof
	_test_eof1: cs = 1; goto _test_eof
	_test_eof2: cs = 2; goto _test_eof
	_test_eof11: cs = 11; goto _test_eof
	_test_eof12: cs = 12; goto _test_eof
	_test_eof3: cs = 3; goto _test_eof
	_test_eof13: cs = 13; goto _test_eof
	_test_eof4: cs = 4; goto _test_eof
	_test_eof14: cs = 14; goto _test_eof
	_test_eof15: cs = 15; goto _test_eof
	_test_eof5: cs = 5; goto _test_eof
	_test_eof16: cs = 16; goto _test_eof
	_test_eof6: cs = 6; goto _test_eof
	_test_eof17: cs = 17; goto _test_eof
	_test_eof7: cs = 7; goto _test_eof
	_test_eof18: cs = 18; goto _test_eof
	_test_eof19: cs = 19; goto _test_eof
	_test_eof20: cs = 20; goto _test_eof
	_test_eof21: cs = 21; goto _test_eof
	_test_eof22: cs = 22; goto _test_eof
	_test_eof23: cs = 23; goto _test_eof
	_test_eof24: cs = 24; goto _test_eof

	_test_eof: {}
	if p == eof {
		switch cs {
		case 9:
			goto tr23
		case 10:
			goto tr24
		case 1:
			goto tr0
		case 2:
			goto tr0
		case 11:
			goto tr24
		case 12:
			goto tr24
		case 3:
			goto tr0
		case 13:
			goto tr24
		case 4:
			goto tr0
		case 14:
			goto tr24
		case 15:
			goto tr25
		case 5:
			goto tr0
		case 16:
			goto tr24
		case 6:
			goto tr14
		case 17:
			goto tr24
		case 7:
			goto tr14
		case 18:
			goto tr24
		case 19:
			goto tr24
		case 20:
			goto tr24
		case 21:
			goto tr24
		case 22:
			goto tr24
		case 23:
			goto tr25
		case 24:
			goto tr25
		}
	}

	_out: {}
	}

//.... lightning/mydump/csv_parser.rl:81

		if cs == 0 {
			parser.logSyntaxError()
			return csvTokNil, nil, errors.New("syntax error")
		}

		if consumedToken != csvTokNil {
			result := data[ts:te]
			parser.buf = data[te:]
			parser.pos += int64(te)
			return consumedToken, result, nil
		}

		if parser.isLastChunk {
			return csvTokNil, nil, io.EOF
		}

		parser.buf = parser.buf[ts:]
		parser.pos += int64(ts)
		p -= ts
		te -= ts
		ts = 0
		if err := parser.readBlock(); err != nil {
			return csvTokNil, nil, errors.Trace(err)
		}
	}
}
