### tidb-lighting configuartion

pprof_port = ""

#
data_source_dir = ""

#
kv_import_backend = "127.0.0.1:8809"

#
pd_backend = "127.0.0.1:8801"

#
[mydumper]
read-block-size = 4096
region-min-size = 13284

[tidb]
host = "127.0.0.1"
port = 8802
user = "root"
password = ""

#
[progress_store]
host = "localhost"
port = 3306
user = "root"
password = ""
database = "_ingest_stat"
