// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lightning/restore/file_checkpoints.proto

package restore

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FCPPBCheckpoints struct {
	Checkpoints          map[string]*FCPPBCheckpoint `protobuf:"bytes,1,rep,name=checkpoints,proto3" json:"checkpoints,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *FCPPBCheckpoints) Reset()         { *m = FCPPBCheckpoints{} }
func (m *FCPPBCheckpoints) String() string { return proto.CompactTextString(m) }
func (*FCPPBCheckpoints) ProtoMessage()    {}
func (*FCPPBCheckpoints) Descriptor() ([]byte, []int) {
	return fileDescriptor_c47ec4f2f281cd62, []int{0}
}

func (m *FCPPBCheckpoints) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FCPPBCheckpoints.Unmarshal(m, b)
}
func (m *FCPPBCheckpoints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FCPPBCheckpoints.Marshal(b, m, deterministic)
}
func (m *FCPPBCheckpoints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FCPPBCheckpoints.Merge(m, src)
}
func (m *FCPPBCheckpoints) XXX_Size() int {
	return xxx_messageInfo_FCPPBCheckpoints.Size(m)
}
func (m *FCPPBCheckpoints) XXX_DiscardUnknown() {
	xxx_messageInfo_FCPPBCheckpoints.DiscardUnknown(m)
}

var xxx_messageInfo_FCPPBCheckpoints proto.InternalMessageInfo

func (m *FCPPBCheckpoints) GetCheckpoints() map[string]*FCPPBCheckpoint {
	if m != nil {
		return m.Checkpoints
	}
	return nil
}

type FCPPBCheckpoint struct {
	Hash                 []byte           `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Status               uint32           `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Engine               []byte           `protobuf:"bytes,4,opt,name=engine,proto3" json:"engine,omitempty"`
	AllocBase            int64            `protobuf:"varint,5,opt,name=alloc_base,json=allocBase,proto3" json:"alloc_base,omitempty"`
	Checksum             uint64           `protobuf:"fixed64,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Kvs                  uint64           `protobuf:"varint,7,opt,name=kvs,proto3" json:"kvs,omitempty"`
	Size                 uint64           `protobuf:"varint,8,opt,name=size,proto3" json:"size,omitempty"`
	Chunks               map[string]int64 `protobuf:"bytes,9,rep,name=chunks,proto3" json:"chunks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FCPPBCheckpoint) Reset()         { *m = FCPPBCheckpoint{} }
func (m *FCPPBCheckpoint) String() string { return proto.CompactTextString(m) }
func (*FCPPBCheckpoint) ProtoMessage()    {}
func (*FCPPBCheckpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_c47ec4f2f281cd62, []int{1}
}

func (m *FCPPBCheckpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FCPPBCheckpoint.Unmarshal(m, b)
}
func (m *FCPPBCheckpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FCPPBCheckpoint.Marshal(b, m, deterministic)
}
func (m *FCPPBCheckpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FCPPBCheckpoint.Merge(m, src)
}
func (m *FCPPBCheckpoint) XXX_Size() int {
	return xxx_messageInfo_FCPPBCheckpoint.Size(m)
}
func (m *FCPPBCheckpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_FCPPBCheckpoint.DiscardUnknown(m)
}

var xxx_messageInfo_FCPPBCheckpoint proto.InternalMessageInfo

func (m *FCPPBCheckpoint) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *FCPPBCheckpoint) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *FCPPBCheckpoint) GetEngine() []byte {
	if m != nil {
		return m.Engine
	}
	return nil
}

func (m *FCPPBCheckpoint) GetAllocBase() int64 {
	if m != nil {
		return m.AllocBase
	}
	return 0
}

func (m *FCPPBCheckpoint) GetChecksum() uint64 {
	if m != nil {
		return m.Checksum
	}
	return 0
}

func (m *FCPPBCheckpoint) GetKvs() uint64 {
	if m != nil {
		return m.Kvs
	}
	return 0
}

func (m *FCPPBCheckpoint) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FCPPBCheckpoint) GetChunks() map[string]int64 {
	if m != nil {
		return m.Chunks
	}
	return nil
}

func init() {
	proto.RegisterType((*FCPPBCheckpoints)(nil), "FCPPBCheckpoints")
	proto.RegisterMapType((map[string]*FCPPBCheckpoint)(nil), "FCPPBCheckpoints.CheckpointsEntry")
	proto.RegisterType((*FCPPBCheckpoint)(nil), "FCPPBCheckpoint")
	proto.RegisterMapType((map[string]int64)(nil), "FCPPBCheckpoint.ChunksEntry")
}

func init() {
	proto.RegisterFile("lightning/restore/file_checkpoints.proto", fileDescriptor_c47ec4f2f281cd62)
}

var fileDescriptor_c47ec4f2f281cd62 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x25, 0xeb, 0x56, 0xb7, 0xaf, 0x8a, 0x25, 0x88, 0x84, 0xa1, 0x50, 0x76, 0x90, 0x5c, 0x6c,
	0x61, 0x53, 0x50, 0x8f, 0x9b, 0x7a, 0x1e, 0x39, 0x7a, 0x19, 0x69, 0x8d, 0x6d, 0x58, 0x97, 0x96,
	0x26, 0x1d, 0xcc, 0x3f, 0x24, 0xf8, 0x2b, 0xa5, 0xd9, 0x70, 0xa5, 0x7a, 0x7b, 0xdf, 0x7b, 0xef,
	0x23, 0xf9, 0x1e, 0x0f, 0x68, 0x2e, 0xd3, 0xcc, 0x28, 0xa9, 0xd2, 0xa8, 0x12, 0xda, 0x14, 0x95,
	0x88, 0x3e, 0x64, 0x2e, 0x56, 0x49, 0x26, 0x92, 0x75, 0x59, 0x48, 0x65, 0x74, 0x58, 0x56, 0x85,
	0x29, 0x26, 0xdf, 0x08, 0xfc, 0xd7, 0xc5, 0x72, 0x39, 0x5f, 0x1c, 0x25, 0xfc, 0x0c, 0x5e, 0xcb,
	0x49, 0x50, 0xe0, 0x50, 0x6f, 0x3a, 0x09, 0xbb, 0xbe, 0xb0, 0x85, 0x5f, 0x94, 0xa9, 0x76, 0xac,
	0xbd, 0x36, 0x5e, 0x82, 0xdf, 0x35, 0x60, 0x1f, 0x9c, 0xb5, 0xd8, 0x11, 0x14, 0x20, 0x3a, 0x62,
	0x0d, 0xc4, 0x37, 0x30, 0xd8, 0xf2, 0xbc, 0x16, 0xa4, 0x17, 0x20, 0xea, 0x4d, 0xfd, 0xee, 0x2b,
	0x6c, 0x2f, 0x3f, 0xf5, 0x1e, 0xd0, 0xe4, 0xab, 0x07, 0xe7, 0x1d, 0x19, 0x63, 0xe8, 0x67, 0x5c,
	0x67, 0x76, 0xfd, 0x94, 0x59, 0x8c, 0x2f, 0xc1, 0xd5, 0x86, 0x9b, 0x5a, 0x13, 0x27, 0x40, 0xf4,
	0x8c, 0x1d, 0xa6, 0x86, 0x17, 0x2a, 0x95, 0x4a, 0x90, 0xbe, 0x75, 0x1f, 0x26, 0x7c, 0x0d, 0xc0,
	0xf3, 0xbc, 0x48, 0x56, 0x31, 0xd7, 0x82, 0x0c, 0x02, 0x44, 0x1d, 0x36, 0xb2, 0xcc, 0x9c, 0x6b,
	0x81, 0xc7, 0x30, 0xb4, 0x77, 0xe9, 0x7a, 0x43, 0xdc, 0x00, 0x51, 0x97, 0xfd, 0xce, 0xf6, 0xa0,
	0xad, 0x26, 0x27, 0x01, 0xa2, 0x7d, 0xd6, 0xc0, 0xe6, 0x43, 0x5a, 0x7e, 0x0a, 0x32, 0xb4, 0x94,
	0xc5, 0xf8, 0x0e, 0xdc, 0x24, 0xab, 0xd5, 0x5a, 0x93, 0x91, 0xcd, 0xf2, 0xaa, 0x7b, 0x65, 0xb8,
	0xb0, 0xf2, 0x3e, 0xc5, 0x83, 0x77, 0xfc, 0x08, 0x5e, 0x8b, 0xfe, 0x27, 0xbb, 0x8b, 0x76, 0x76,
	0x4e, 0x2b, 0xa9, 0xf9, 0xfd, 0xdb, 0x2c, 0x95, 0x26, 0xab, 0xe3, 0x30, 0x29, 0x36, 0x51, 0x29,
	0x55, 0x9a, 0xf0, 0x32, 0x32, 0xf2, 0x3d, 0xbe, 0x3d, 0x56, 0xe3, 0x4f, 0x49, 0x62, 0xd7, 0x96,
	0x62, 0xf6, 0x13, 0x00, 0x00, 0xff, 0xff, 0xfa, 0xe5, 0xe4, 0xc3, 0x40, 0x02, 0x00, 0x00,
}
